name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-job1:
    name: Test Step1
    runs-on: ubuntu-latest
    steps:
      - run: echo "I am running now" && sleep 50

  test-job2:
    name: Test Step2
    runs-on: macos-latest
    needs: test-job1
    steps:
      - run: echo "I am running now on macos" && sleep 50