name: Test

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

jobs:
  test-job:
    name: Test Step
    runs-on: ubuntu-latest
    steps:
      - run: echo "I am running now"