name: Test

on:
  workflow_run:
    workflows:
      - CI test
    types:
      - completed

jobs:
  test-job:
    name: Test Step
    runs-on: macos-latest
    steps:
      - run: echo "I am running now on macos-latest"