name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  snapshot_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v18.4

     - name: List all changed files
        id: blah
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo $file
            if [[ $file == "common-ui/"* ]] || [[ $file == "pages/"* ]] || [[ $file == "widgets/"* ]]
            then
            echo ::set-output name=status::success
            fi
          done

      - name: Perform action when test_directory changes
        if: steps.blah.outputs.status == 'success'
        run: |
          echo "test_directory has changed."