name: Test

on:
  workflow_run:
    workflows:
      - CI test
    types:
      - completed
  push:
    branches: [ main ]

jobs:
  test-job:
    name: Test Step
    runs-on: ubuntu-latest
    steps:
      - run: echo "I am running now"